name: GitHub Actions Demo

on:
  push:
    tags:
      - "v*.*.*"  

permissions:
  contents: write

jobs:
  build_and_upload_binaries:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: go build -o b64w386 .
        env:
          GOOS: "windows"
          GOARCH: "386"
      - run: go build -o b64warm .
        env:
          GOOS: "windows"
          GOARCH: "arm"
      - run: go build -o b64warm64 .
        env:
          GOOS: "windows"
          GOARCH: "arm64"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            b64w386
            b64warm
            b64warm64